name: Node.js CI (Npm)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install --frozen-lockfile

      - name: Fix eslint permissions
        run: chmod +x ./node_modules/.bin/*

      - name: Lint code
        run: npm run lint

      - name: Run tests
        run: npm test
      
      - name: Run coverage
        run: npm run coverage

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage
      
      - name: Deploy to Render
        uses: render-examples/github-action@v1
        with:
          apiKey: rnd_UgKpcm1z1MaV81ExYBEx6gwV4mY7
          serviceId: srv-d427d7e3jp1c73adcm4g

